name: Continuous Testing and Publication

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-js-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22.x
          - 24.x

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Run JS validate
        uses: ./actions/js/validate
        with:
          node-version: '22.x'
          skip-eslint: 'true'
          npm-options: '--legacy-peer-deps'

      - name: Run JS tests
        uses: ./actions/js/test
        with:
          node-version: ${{ matrix.node-version }}
          npm-options: '--legacy-peer-deps'

  publish-js-package:
    needs:
      - run-js-tests
    runs-on: ubuntu-latest
    if: (github.repository != 'Exabyte-io/template-definitions') && (github.ref_name == 'main')

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish JS release
        uses: ./actions/js/publish
        with:
          node-version: 22.x
          npm-token: ${{ secrets.GITHUB_TOKEN }}
          registry-url: 'https://npm.pkg.github.com'
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          verify-tests: 'false'
          npm-options: '--legacy-peer-deps'
